image:
  repository: docker-local.artifactory.ameren.com/gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.1
  pullPolicy: Always

instance: ctsstore

userstore:
  enabled: false

storageClass: fast

podAntiAffinity: hard

runPostSetupJob: false

replicas: 1

topologyKey: "failure-domain.beta.kubernetes.io/zone"
