image:
  repository: docker-local.artifactory.ameren.com/gcr.io/forgerock-io/amster
  #repository: gcr.io/engineering-devops/amster
  tag: 6.5.1
  pullPolicy: Always
  
config:
  importPath: /git/config/6.5/cdm/m-cluster/am
  exportPath: /tmp/amster

amadminPassword: TB79tvzp7AUSM9aF

ctsStores: ctsstore-0.ctsstore:1389,ctsstore-1.ctsstore:1389
ctsPassword: password

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi
