image:
  repository: docker-local.artifactory.ameren.com/gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.1
  pullPolicy: Always

gcs:
  enabled: false
  bucket: gs://forgeops/dj-backup/s-cluster

s3:
  enabled: false
  bucket: s3://ciam-dev-bucket  

nfs:
  server: fs-70c020f1.efs.us-east-1.amazonaws.com
  #server: fs-ab7e17e1.efs.us-east-1.amazonaws.com
  path: /export

backup:
  pvcName: ds-backup
  storageSize: 100Gi

createPVC: true

slackUrl: undefined
