image:
 #repository: gcr.io/forgerock-io/openig
  repository: docker-local.artifactory.ameren.com/gcr.io/forgerock-io/openig
  tag: 6.5.1
  pullPolicy: IfNotPresent

config:
  name: frconfig
  path: /git/config/6.5/default/ig/basic-sample
  strategy: git

# Tomcat JVM options.
catalinaOpts:  >
  -server -Xms1g -Xmx1g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log -Dhttp.proxyHost=c1184651648.saasprotection.com -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=\"172.27.212.0/23|169.254.169.254|169.254.170.2|/var/run/docker.sock|*.soock|ec2.internal|localhost|.eks.amazonaws.com|.ameren.com|127.0.0.1|10.0.0.0/8|1772.28.32.0/20|172.28.48.0/20|172.27.0.0/17|172.26.0.0/16|openam\" -Dhttps.proxyHost=c1184651648.saasprotection.com -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts=\"172.27.212.0/23|169.254.169.254|169.254.170.2|/var/run/docker.sock|*.soock|ec2.internal|localhost|.eks.amazonaws.com|.ameren.com|127.0.0.1|10.0.0.0/8|1772.28.32.0/20|172.28.48.0/20|172.27.0.0/17|172.26.0.0/16|openam\"

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

replicaCount: 2
