image:
 #repository: gcr.io/forgerock-io/openig
  repository: docker-local.artifactory.ameren.com/gcr.io/forgerock-io/openig
  tag: 6.5.1
  pullPolicy: IfNotPresent

config:
  name: frconfig
  path: /git/config/6.5/default/ig/ig-web
  strategy: git

# Tomcat JVM options.
catalinaOpts:  >
  -server -Xms1g -Xmx1g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

replicaCount: 2


# These are both used to form the FQDN for the load balancer.  See _helpers.tpl
component: openig-internal

service:
  name: openig-internal
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

secret:
    name: openig-internal-secrets-env  
