# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  # If you want to run more than one IG deployment in the same namespace, change the deployment name
  # below to the {{ template "fullname" . }} to make the name unique.
  name:  {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    vendor: forgerock
    component: {{ .Values.component }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.component }}
        vendor: forgerock
    spec:
      {{ if eq .Values.config.strategy  "git" }}
      initContainers:
      - name: git-init
        image: {{ .Values.gitImage.repository }}:{{ .Values.gitImage.tag }}
        imagePullPolicy: {{ .Values.gitImage.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
      {{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
        - configMapRef:
            name:  {{ .Values.component }}-{{ .Release.Name }}  
        - secretRef:
            name: {{ default "frconfig" .Values.config.name }}-platform
        - secretRef:
            name: {{ default "openig-secrets-env" .Values.secret.name  }}
        env:
        - name: "HTTPS_PROXY"
          value: "c1184651648.saasprotection.com:8080"
        - name: "NO_PROXY"
          value: "172.27.212.0/23,169.254.169.254,169.254.170.2,/var/run/docker.sock,*.soock,ec2.internal,localhost,.eks.amazonaws.com,.ameren.com,127.0.0.1,10.0.0.0/8,1772.28.32.0/20,172.28.48.0/20,172.27.0.0/17,172.26.0.0/16"
        - name: OPENIG_BASE
          value: "{{ .Values.config.path }}"
        - name: CATALINA_OPTS
          value: "{{ .Values.catalinaOpts }}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AGENT_UID
          value: "{{ .Values.agent.username }}"
        - name: AGENT_SECRET_ID
          value: "{{ .Values.agent.password }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        volumeMounts:
        {{ if eq .Values.config.strategy  "git" }}
        - name: git
          mountPath: /git
        {{ end }}
        - name: conf  
          mountPath: /usr/local/tomcat/conf/web.xml
          subPath: web.xml
        livenessProbe:
          httpGet:
           path: /kube/liveness
           port: {{ .Values.service.internalPort }}
          timeoutSeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /kube/readiness
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 5
        resources:
{{ toYaml .Values.resources | indent 12 }}
      # audit logging containers
      {{- range .Values.auditLogs }}
      - name: {{ .name }}
        image: busybox
        env:
        - name: LOGFILE
          value: {{ .path }}
        args: [bin/sh, -c, 'while true; do if [ -e $LOGFILE ]; then tail -n+1 -f $LOGFILE; fi; sleep 5; done' ]
        volumeMounts:
        - name: logs
          mountPath: /tmp/logs
      {{- end }}
      volumes:
      - name: logs
        emptyDir: {}
      - name: conf
        configMap:
          name: {{ .Values.component }}
          items:
          - key: web.xml
            path: web.xml  
      {{ if eq .Values.config.strategy  "git" }}
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName:  {{ default "frconfig" .Values.config.name }}
      {{ end }}
